package swagger

// SwaggerJson represents the json generated by the swagger docs
type SwaggerJson struct {
	Swagger  string          `json:"swagger"`
	Host     string          `json:"host"`
	BasePath string          `json:"basePath"`
	Schemes  []string        `json:"schemes"`
	Consumes []string        `json:"consumes"`
	Produces []string        `json:"produces"`
	Paths    map[string]Path `json:"paths"`
}
type RestApi struct {
	Description string              `json:"description"`
	Tags        []string            `json:"tags"`
	OperationID string              `json:"operationId"`
	Responses   map[string]Response `json:"responses"`
}
type Path struct {
	Get    *RestApi `json:"get"`
	Post   *RestApi `json:"post"`
	Put    *RestApi `json:"put"`
	Delete *RestApi `json:"delete"`
	Update *RestApi `json:"update"`
}
type Schema struct {
	Ref string `json:"$ref"`
}
type Response struct {
	Description string `json:"description"`
	Schema      Schema `json:"schema"`
}
