package swagger

// SwaggerJson represents the json generated by the swagger docs
type SwaggerJson struct {
	Swagger string          `json:"swagger"` // represents the swagger version
	Host    string          `json:"host"`    // url of the host
	Paths   map[string]Path `json:"paths"`   // represents the endpoints in swagger
}
type RestApi struct {
	Description string              `json:"description"` // description of the API
	Tags        []string            `json:"tags"`        // tags used to group the API
	OperationID string              `json:"operationId"` // unique id to represent the API
	Responses   map[string]Response `json:"responses"`   // expected responses for the API
}
type Path struct {
	Get    *RestApi `json:"get"`    // GET endpoint
	Post   *RestApi `json:"post"`   // POST endpoint
	Put    *RestApi `json:"put"`    // PUT endpoint
	Delete *RestApi `json:"delete"` // DELETE endpoint
	Update *RestApi `json:"update"` // UPDATE endpoint
}

type Response struct {
	Description string `json:"description"` // description for the specific response
}
