package fetcher

// SwaggerJson represents the json generated by the swagger docs
type SwaggerJson struct {
	Swagger     string   `json:"swagger"`
	Info        any      `json:"info"`
	Host        string   `json:"host"`
	BasePath    string   `json:"basePath"`
	Schemes     []string `json:"schemes"`
	Consumes    []string `json:"consumes"`
	Produces    []string `json:"produces"`
	Paths       any      `json:"paths"`
	Definitions any      `json:"definitions"`
}
